/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HeroHub;

import java.util.HashMap;

import java.util.Map;

import spark.ModelAndView;

import static spark.Spark.*;

public class App {
    public static void main(String[] args) {
        staticFileLocation("/public");

        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "herohub.hbs");
        }, new HandlebarsTemplateEngine());

        get("/", (request, response) -> {
            Map<String, Object> model = new HashMap<String, Object>();
            return new ModelAndView(new HashMap(), "squadhub.hbs");
        }, new HandlebarsTemplateEngine());
    }
}
